### ISSUE TITLE
How to insert date field in HashMap-Getting wrong output

### ISSUE THREAD

**Issue by AshwinAgrawal16** [nathan-russell/hashmap#10]
Please have a look at the below code and output:
Code:
H3 <- hashmap((as.Date("10/9/2009", "%m/%d/%Y")), 1)
H3$data()

Output
14526 
    1 

What is the correct way to insert date field, because its giving wrong output.

Regards
Ashwin

**Comment by nathan-russell** [comment]
The `hashmap` object *is* storing the keys correctly -- note how the `Date` class is preserved below: 

```r
H3 <- hashmap::hashmap(as.Date("10/9/2009", "%m/%d/%Y"), 1)

H3
##       (Date) => (numeric)  
## [2009-10-09] => [+1.000000]

H3$keys()
# [1] "2009-10-09"

class(H3$keys())
# [1] "Date"

H3$data.frame()
#         Keys Values
# 1 2009-10-09      1

H3$data()
# 14526 
#     1 

names(H3$data())
# [1] "2009-10-09"

class(names(H3$data()))
# [1] "Date"
``` 

The confusion comes from the fact that R normally coerces the `names` attribute to the character class: 

```r
x <- 1:3; names(x) <- Sys.Date() + 1:3; x
# 2017-07-07 2017-07-08 2017-07-09 
#          1          2          3 

class(names(x))
# [1] "character"
```

**Comment by AshwinAgrawal16** [comment]
Thanks for the explanation @nathan-russell
