### ISSUE TITLE
Error in rsqlite_send_query(conn@ptr, statement) :    external pointer is not valid

### ISSUE THREAD

**Issue by BusinessKidTriesR** [nathan-russell/hashmap#8]
Hi, I am doing a pretty basic assignment where I read in a csv file, but now I can't query anything. Any thoughts?

> setwd("/users/monicahealy/desktop/assignment4")
> 
> library("RSQLite")
> db<-dbConnect(SQLite(), dbname="booksDB.sqlite")
> dbWriteTable(conn = db, name = "List_Books", value = "books.csv", row.names = FALSE, header = TRUE)
[1]TRUE
> dbGetQuery(con, "SELECT author FROM List_Books")
**Error in rsqlite_send_query(conn@ptr, statement) : 
  external pointer is not valid**

**Comment by nathan-russell** [comment]
You don't appear to be using the `hashmap` package in your code?
